MinProApi/JfApi/urls.py
from django.urls import path
from . import views

app_name='jfapi'
urlpatterns = [
    path('',views.mywork,name='mywork'),
    path('enterview/',views.enterview,name="enteriew"),
    path('jfview/',views.jfview,name="jfview"),
    path('mywork/',views.mywork,name='mywork'),
    path('index/',views.indexview,name='index')
]

MinProApi/MinProApi/urls.py
from django.contrib import admin
from django.urls import path
from JfApi import urls
from django.urls.conf import include

urlpatterns = [
    path('',include('JfApi.urls')),
    path('admin/', admin.site.urls),
]

MinProApi/templates/ENTER.html
<h1>计算器类型选择页面1-6</h1>

<form action="{% url 'jfapi:enteriew' %}" method="post">

<select name="NUM_CHOIC">
<option value="0">不定积分</option>
<option value="1">函数求导</option>
<option value="2">因式分解</option>
<option value="3">定积分</option>
<option value="4">求极限</option>
<option value="5">表达式化简</option>
</select>
<input type="submit" value="提交">
</form>

<a href="{% url 'jfapi:mywork' %}">去往我的小花园</a>

MinProApi/templates/bdjf.html
<h1>不定积分</h1>

<form action="{% url 'jfapi:jfview' %}" method="post">

<input type="text" name="NUM_CHOIC" value="0" readonly>
<input type="text" name="function" placeholder="表达式">
<input type="text" name="var" placeholder="自变量">

<input type="submit" value="提交">
</form>

MinProApi/templates/djf.html
<h1>定积分</h1>

<form action="{% url 'jfapi:jfview' %}" method="post">

<input type="text" name="NUM_CHOIC" value="3" readonly>
<input type="text" name="function" placeholder="表达式">
<input type="text" name="var" placeholder="自变量">
<input type="text" name="a" placeholder="积分左侧">
<input type="text" name="b" placeholder="积分右侧">
<input type="submit" value="提交">
</form>

MinProApi/templates/hj.html
<h1>化简</h1>

<form action="{% url 'jfapi:jfview' %}" method="post">

<input type="text" name="NUM_CHOIC" value="5" readonly>
<input type="text" name="function" placeholder="表达式">
<input type="submit" value="提交">
</form>

MinProApi/templates/hsqd.html
<h1>函数求导</h1>

<form action="{% url 'jfapi:jfview' %}" method="post">

<input type="text" name="NUM_CHOIC" value="1" readonly>
<input type="text" name="function" placeholder="表达式">
<input type="text" name="var" placeholder="自变量">
<input type="text" name="order" placeholder="阶数">
<input type="submit" value="提交">
</form>

MinProApi/templates/jx.html
<h1>极限计算器</h1>

<form action="{% url 'jfapi:jfview' %}" method="post">

<input type="text" name="NUM_CHOIC" value="4" readonly>
<input type="text" name="function" placeholder="表达式">
<input type="text" name="var" placeholder="自变量">
<input type="text" name="limi" placeholder="极限类型0-1-2">
<input type="text" name="val" placeholder="展开点">

<input type="submit" value="提交">
</form>

MinProApi/templates/result.html
<h1>结果页面</h1>

{% for m in msg %}
<h1>{{msg}}</h1>
{% endfor %}

<img src="{{ANS_IMG}}">

MinProApi/templates/ysfj.html
<h1>因式分解</h1>

<form action="{% url 'jfapi:jfview' %}" method="post">

<input type="text" name="NUM_CHOIC" value="2" readonly>
<input type="text" name="function" placeholder="表达式">
<input type="submit" value="提交">
</form>